import { Ebook } from "./types";

export const sampleEbooks: Ebook[] = [
  {
    id: "1",
    title: "Walking in Faith",
    author: "Grace Thompson",
    description: "A 30-day devotional journey that will deepen your relationship with God and strengthen your daily walk of faith. Each day offers scripture, reflection, and prayer prompts.",
    price: 1299,
    cover_url: "",
    file_url: "",
    category: "Devotionals",
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Understanding the Gospels",
    author: "Rev. David Okonkwo",
    description: "A comprehensive study guide through the four Gospels, with historical context, theological insights, and practical applications for modern believers.",
    price: 1999,
    cover_url: "",
    file_url: "",
    category: "Bible Study",
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    title: "The Prodigal's Return",
    author: "Sarah Mitchell",
    description: "A moving Christian fiction novel about redemption, forgiveness, and the unending love of a father — both earthly and heavenly.",
    price: 999,
    cover_url: "",
    file_url: "",
    category: "Christian Fiction",
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Little Prayers for Little Hearts",
    author: "Joy Adeyemi",
    description: "A beautifully illustrated prayer book for children aged 3-8, teaching them to talk to God in their own words.",
    price: 799,
    cover_url: "",
    file_url: "",
    category: "Children",
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    title: "The Armor of God",
    author: "Pastor James Eze",
    description: "An in-depth study of Ephesians 6:10-18, equipping believers to stand firm against spiritual warfare with practical strategies.",
    price: 1499,
    cover_url: "",
    file_url: "",
    category: "Prayer",
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    title: "Foundations of Grace",
    author: "Dr. Emmanuel Nwosu",
    description: "Exploring the doctrine of grace through scripture and church history, showing how grace transforms every area of life.",
    price: 1799,
    cover_url: "",
    file_url: "",
    category: "Theology",
    featured: false,
    created_at: new Date().toISOString(),
  },
];
