// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-ebooks.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-ebooks.ts
var search_ebooks_default = defineTool({
  name: "search_ebooks",
  title: "Search ebooks",
  description: "Search the approved ebook catalogue by title, author, description or category.",
  inputSchema: {
    query: z.string().trim().max(200).optional().describe("Free-text search over title, author and description."),
    category: z.string().trim().max(100).optional().describe("Filter by category, e.g. 'Free Resources'."),
    limit: z.number().int().min(1).max(50).default(10).describe("Maximum number of results.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("ebooks").select("id,title,author,description,price,category,featured,cover_url").eq("approval_status", "approved").limit(limit ?? 10);
    if (category) q = q.eq("category", category);
    if (query) q = q.or(`title.ilike.%${query}%,author.ilike.%${query}%,description.ilike.%${query}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((b) => ({ ...b, price_kwacha: b.price }));
    return {
      content: [{ type: "text", text: rows.length ? JSON.stringify(rows, null, 2) : "No ebooks matched." }],
      structuredContent: { ebooks: rows }
    };
  }
});

// src/lib/mcp/tools/get-ebook.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_ebook_default = defineTool2({
  name: "get_ebook",
  title: "Get ebook details",
  description: "Fetch full details for one approved ebook by its id.",
  inputSchema: { id: z2.string().uuid().describe("Ebook id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("ebooks").select("id,title,author,description,price,category,featured,cover_url,approval_status,created_at").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Ebook not found." }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { ebook: data } };
  }
});

// src/lib/mcp/tools/my-library.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var my_library_default = defineTool3({
  name: "my_library",
  title: "My library",
  description: "List the ebooks the signed-in user owns and can download.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_ebook_access").select("created_at, ebooks(id,title,author,category,price,cover_url)").order("created_at", { ascending: false }).limit(100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const items = data ?? [];
    return {
      content: [{ type: "text", text: items.length ? JSON.stringify(items, null, 2) : "Your library is empty." }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/tools/my-orders.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var my_orders_default = defineTool4({
  name: "my_orders",
  title: "My orders",
  description: "List the signed-in user's orders with status, total in Kwacha and any failure reason.",
  inputSchema: {
    status: z3.enum(["pending", "completed", "failed"]).optional().describe("Filter by order status."),
    limit: z3.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("orders").select("id,status,total,payment_reference,failure_reason,created_at,items").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const orders = data ?? [];
    return {
      content: [{ type: "text", text: orders.length ? JSON.stringify(orders, null, 2) : "No orders yet." }],
      structuredContent: { orders }
    };
  }
});

// src/lib/mcp/tools/author-sales.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var author_sales_default = defineTool5({
  name: "author_sales_summary",
  title: "Author sales summary",
  description: "Sales, platform fees, payouts and available balance for the signed-in author's approved books (Kwacha).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const userId = ctx.getUserId();
    if (!userId) return { content: [{ type: "text", text: "Could not determine the signed-in user." }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("calculate_author_earnings", { _author_id: userId });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const summary = Array.isArray(data) ? data[0] : data;
    return {
      content: [{ type: "text", text: JSON.stringify(summary ?? {}, null, 2) }],
      structuredContent: { summary: summary ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "urevgkspvzyazikrfmvp";
var mcp_default = defineMcp({
  name: "the-christian-ebook-shelf",
  title: "The Christian Ebook Shelf",
  version: "0.1.0",
  instructions: "Tools for E Library, a Zambian Christian ebook shop. Prices are in Zambian Kwacha (K). Use search_ebooks and get_ebook to explore the catalogue, my_library and my_orders for the signed-in customer's purchases, and author_sales_summary for an author's earnings.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_ebooks_default, get_ebook_default, my_library_default, my_orders_default, author_sales_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
