
ALTER TABLE public.post_schedules
  ADD COLUMN IF NOT EXISTS target_account_ids UUID[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS image_count INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS style_hints TEXT,
  ADD COLUMN IF NOT EXISTS audience TEXT;
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;
